version: 2.1
jobs:
  build:
    docker:
      - image: girder/girder_test:latest-py3
      - image: circleci/mongo:4.0-ram
        command: ["mongod", "--storageEngine", "ephemeralForTest", "--dbpath", "/dev/shm/mongo"]
    steps:
      - checkout
      - run:
          name: Lint Python
          command: tox
      - run:
          name: Lint web client
          command: |
            npm install
            npm run lint
          working_directory: covalic/web_client
      - run:
          name: Lint web external
          command: |
            npm install
            npm run lint
          working_directory: covalic/web_external
